### ISSUE TITLE
Sending ping packet back

### ISSUE THREAD

**Issue by abzh423** [AnchorMC/Anchor#7]
As I understand we don't send any packets yet. But we can receive then on TCP socket, as I saw we have a structure with listener for that.

I would like to start working on it.

And by the way, here is what I got from trying to understand the initial packet from the client:

> `00010000 - size of the packet
> 
> 00000000 - Packet ID 
> 
> 11111010 - protocol version (+512 and you will get it) (https://wiki.vg/Protocol_version_numbers)
> 
> 00000101 - always stays 5 (idk what is this)
> 
> 00001001 - 9 likely the length of the server address
> 
> 01101100 01101111 01100011 01100001 01101100 01101000 01101111 01110011 01110100 - server address 
> 
> 00010011 10001000 - server port
> 
> 00000010 - next state`

The repo for some reason is quite still

**Comment by PassTheMayo** [comment]
I used to work on this repository a lot a long time ago, but I decided to restart from scratch due to poor code structure and I haven't worked on it much. I would like to get back into it at some point but I have a lot going on at the moment. Also, the Handshake packet follows this format: https://wiki.vg/Protocol#Handshake.

**Comment by abzh423** [comment]
> I used to work on this repository a lot a long time ago, but I decided to restart from scratch due to poor code structure and I haven't worked on it much. I would like to get back into it at some point but I have a lot going on at the moment. Also, the Handshake packet follows this format: https://wiki.vg/Protocol#Handshake.

Yeap, for some reason, when getting the packets there are strange numbers that pop out.
And it's okay, I guess will focus on something else. Goodbye and farewell.
